In [92]:
import pandas as pd
import numpy as np

df = pd.read_csv('submission_3.csv')
threshold = 0.22
df.head(50)

                  id                 landmarks
0   000088da12d664db   428 0.09464637190103531
1   0001623c6d808702   496 0.14476759731769562
2   0001bbb682d45002  538 0.056128013879060745
3   0002362830cfe3a3   878 0.09213665127754211
4   000270c9100de789   996 0.08152172714471817
5   0002b0fab5d3ccc4    960 0.1086178869009018
6   000396be3c24830a  471 0.027322400361299515
7   000506dc6ab3a40e   960 0.05993445962667465
8   0005292fc4b005a3     0 0.06807159632444382
9   0005456a82264bc8  328 0.029965639114379883
10  00055cf2bfb5594a   478 0.08710933476686478
11  000664eed4a70821  456 0.045828189700841904
12  0006aea5b6f4eaaa  1113 0.14221800863742828
13  0006bbfa00dd6c0f   996 0.43033185601234436
14  0008aee1c0abed9d   543 0.25617146492004395
15  0008de5f3c25d563    95 0.08228882402181625
16  00094466c9f054f4    960 0.2807924151420593
17  0009f09a69405693  1181 0.07621797174215317
18  000a7f4a25af7558   960 0.03642033785581589
19  000a9180e4dc8705   355 0.13774317502975464
20  000aee511bc53f8b   944 0.21156929433345795
21  000b55ddc1160a12  1310 0.04288718104362488
22  000c08916d77b8ba   845 0.07710243761539459
23  000c2a80838aabff    1394 0.352319598197937
24  000dad8a776a3631  878 0.057973384857177734
25  000e30f1e5b32741  1293 0.03369363769888878
26  000e47a43eb8a307   233 0.05943235754966736
27  00108ec72b2344bd   117 0.20814557373523712
28  0010ab920bac8640   428 0.12825199961662292
29  0010e7cad366d6fa    878 0.2300456464290619
30  001119140e4bb030    428 0.3342165946960449
31  00129c981f8e343f                       NaN
32  0013a06d20c7839f   304 0.04922211170196533
33  001490806c884d96      0 0.0726890042424202
34  0014be4f4910bbe6    497 0.1790587306022644
35  0014ea5d819557be   263 0.10268475115299225
36  0015898890608086   867 0.24456320703029633
37  001645116c77f6be  1107 0.04222440347075462
38  001693c1ea808396   878 0.10968802124261856
39  00169f449b4c60c0   258 0.11219722777605057
40  0016de8fd1c3eab6  1222 0.20802262425422668
41  0017719d5bba733c    81 0.09423802047967911
42  0017d8ef2a3acd3c    960 0.4655686616897583
43  0017deb491895bba   1472 0.2783591151237488
44  001800346d31f711   355 0.31445562839508057
45  00181e5553bf2564  1054 0.04652043431997299
46  0018761e6c424bd4   388 0.05399666354060173
47  0018893bd38632df   376 0.10738342255353928
48  0018b97bd2b24bd7   838 0.09973012655973434
49  0018d55375fc9760   867 0.26606816053390503

In [93]:
df_tmp = df.dropna(how = 'any')
df_tmp['landmark_id'] = df_tmp['landmarks'].apply(lambda x: int(str(x).split(' ')[0]))
df_tmp['confidence'] = df_tmp['landmarks'].apply(lambda x: float(str(x).split(' ')[-1]))
df_tmp[['confidence']].describe()

C:\Users\Student\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Student\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

          confidence
count  115780.000000
mean        0.153616
std         0.156203
min         0.003705
25%         0.054527
50%         0.099653
75%         0.188852
max         0.999997

In [94]:
df_tmp = df_tmp[df_tmp['confidence'] > threshold]
df_tmp = df_tmp.drop(['landmark_id', 'confidence'], axis = 1)
df = df[['id']].merge(df_tmp, how = 'left', on = 'id')
print(df.shape)
df.head(50)

(117703, 2)

                  id                landmarks
0   000088da12d664db                      NaN
1   0001623c6d808702                      NaN
2   0001bbb682d45002                      NaN
3   0002362830cfe3a3                      NaN
4   000270c9100de789                      NaN
5   0002b0fab5d3ccc4                      NaN
6   000396be3c24830a                      NaN
7   000506dc6ab3a40e                      NaN
8   0005292fc4b005a3                      NaN
9   0005456a82264bc8                      NaN
10  00055cf2bfb5594a                      NaN
11  000664eed4a70821                      NaN
12  0006aea5b6f4eaaa                      NaN
13  0006bbfa00dd6c0f  996 0.43033185601234436
14  0008aee1c0abed9d  543 0.25617146492004395
15  0008de5f3c25d563                      NaN
16  00094466c9f054f4   960 0.2807924151420593
17  0009f09a69405693                      NaN
18  000a7f4a25af7558                      NaN
19  000a9180e4dc8705                      NaN
20  000aee511bc53f8b                      NaN
21  000b55ddc1160a12                      NaN
22  000c08916d77b8ba                      NaN
23  000c2a80838aabff   1394 0.352319598197937
24  000dad8a776a3631                      NaN
25  000e30f1e5b32741                      NaN
26  000e47a43eb8a307                      NaN
27  00108ec72b2344bd                      NaN
28  0010ab920bac8640                      NaN
29  0010e7cad366d6fa   878 0.2300456464290619
30  001119140e4bb030   428 0.3342165946960449
31  00129c981f8e343f                      NaN
32  0013a06d20c7839f                      NaN
33  001490806c884d96                      NaN
34  0014be4f4910bbe6                      NaN
35  0014ea5d819557be                      NaN
36  0015898890608086  867 0.24456320703029633
37  001645116c77f6be                      NaN
38  001693c1ea808396                      NaN
39  00169f449b4c60c0                      NaN
40  0016de8fd1c3eab6                      NaN
41  0017719d5bba733c                      NaN
42  0017d8ef2a3acd3c   960 0.4655686616897583
43  0017deb491895bba  1472 0.2783591151237488
44  001800346d31f711  355 0.31445562839508057
45  00181e5553bf2564                      NaN
46  0018761e6c424bd4                      NaN
47  0018893bd38632df                      NaN
48  0018b97bd2b24bd7                      NaN
49  0018d55375fc9760  867 0.26606816053390503

In [95]:
df.to_csv('submission_6.csv', index = False)